name: Build

on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        config: [
          { target: android, os: ubuntu-latest, tasks: testDebugUnitTest testReleaseUnitTest, continueOnError: false },
          { target: apple, os: macos-latest, tasks: iosX64Test iosSimulatorArm64Test macosX64Test macosArm64Test tvosX64Test tvosSimulatorArm64Test watchosX64Test watchosSimulatorArm64Test, continueOnError: false },
          { target: windows, os: windows-latest, tasks: windowsTest, continueOnError: false },
          { target: linux, os: ubuntu-latest, tasks: linuxTest, continueOnError: false }
        ]
    runs-on: ${{ matrix.config.os }}
    name: Build ${{ matrix.config.target }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        uses: gradle/gradle-build-action@v2
        #continue-on-error: ${{ matrix.config.continueOnError }}
        with:
          arguments: build test

      #- name: Test ${{ matrix.config.target }} targets
      #  continue-on-error: ${{ matrix.config.continueOnError }}
      #  run: ./gradlew ${{ matrix.config.tasks }}
