
name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build test

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#          arguments: build test jacocoTestReport sonar

      # gradle test jacocoTestReport sonarqube
      # later upload via gradle?!
      # https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
#      - name: Upload base
#        uses: actions/upload-artifact@v3
#        with:
#         name: base
#         path: kompack-base/build/libs
#      - name: Upload kotlin-serialization
#        uses: actions/upload-artifact@v3
#        with:
#          name: base
#          path: kompack-kotlin-serialization/build/libs